import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '../globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { dir } from 'i18next'
import { languages } from '@/i18n/settings'
import { cn } from '@/lib/utils'
import { ModalProvider } from '@/components/providers/modal-provider'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }))
}

export default function RootLayout({
  children,
  params: { lang },
  ...props
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: string
  }
}>) {
  console.log('props', props)
  return (
    <html lang={lang} dir={dir(lang)} suppressHydrationWarning>
      <body className={cn('text-common', font.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ModalProvider />
        </ThemeProvider>
      </body>
    </html>
  )
}
